var json_ExistingFarms_0 = {
"type": "FeatureCollection",
"name": "ExistingFarms_0",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "FOOD ROOF Farm", "description": "<video width='320' height='180' controls preload='auto'><source src='Video/FoodRoof.mp4'></video><p>FOOD ROOF Farm, the first rooftop farm in St. Louis, Missouri, USA, is a model for urban agriculture, sustainable building, stormwater management and community development.  This exciting 8,500 square foot rooftop is a dynamic example of a green infrastructure, and so much more.</p>" }, "geometry": { "type": "Point", "coordinates": [ -90.1980205, 38.633941, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Fresh Starts Community Garden", "description": "<p>Fresh Starts is an award winning community garden in the JeffVanderLou neighborhood founded and run by the dynamic Rosie Willis. We maintain 15 garden beds at Fresh Starts sourcing hyper-local, fresh produce directly to St. Louis MetroMarket's Saturday site located just a few blocks from the garden.</p>" }, "geometry": { "type": "Point", "coordinates": [ -90.2178557, 38.6423165, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "School Garden: Flance Early Learning Center", "description": "<p>We partner with the Flance Early Learning Center to cultivate and maintain an integrated schoolyard garden that features 20 raised garden beds with integrated sensory garden components, a picnic area, and composting site.</p>" }, "geometry": { "type": "Point", "coordinates": [ -90.2043537, 38.6403565, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Kerr FOOD ROOF", "description": "<video width='320' height='180' controls preload='auto'><source src='Video/KERR.mp4'></video><p>In partnership with the William A. Kerr Foundation, we are converting their sedum green roof into a thriving FOOD ROOF featuring one hydroponic tower, 35 modular smart pots, 6 railing planters and 1 edible living wall.</p>" }, "geometry": { "type": "Point", "coordinates": [ -90.1819729, 38.6374365, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": ".ZACK FOOD ROOF", "description": "<p>A collaboration with the Kranzberg Arts Foundation, the .ZACK FOOD ROOF farm grows a wide variety of vegetables, fruits, herbs and edible flowers that sources fresh, healthy produce to the Arts Foundation venues as well as the immediate food desert community.</p>" }, "geometry": { "type": "Point", "coordinates": [ -90.226299, 38.6365159, 0.0 ] } },
{ "type": "Feature", "properties": { "Name": "Busch Stadium", "description": "<p>Cardinals Nation grows local food! We're showcasing urban agriculture's versatility at Busch Stadiumby maintaining hydroponic towers and modular planters providing chefs at the stadium direct access to fresh ingredients.</p>" }, "geometry": { "type": "Point", "coordinates": [ -90.1928209, 38.6226188, 0.0 ] } }
]
}
